import type {Metadata} from "next";
import Link from "next/link";
import {AccessGapTable} from "@/components/AccessGapTable";
import {LazyAccessibilityMap} from "@/components/LazyAccessibilityMap";
import {DataBadge} from "@/components/DataBadge";
import {IslandCards} from "@/components/IslandCards";
import {Metric} from "@/components/Metric";
import {ResultSourcesLink} from "@/components/ResultSourcesLink";
import {SourceMethodPanel} from "@/components/SourceMethodPanel";
import {profiles} from "@/lib/data";
export const metadata:Metadata={alternates:{canonical:"/"}};
export default function Home(){const {summary,islands,municipalities,metadata}=profiles;const airStations=islands.reduce((n,i)=>n+i.air_station_count,0);return <>
<section className="hero"><div className="hero-copy"><div className="hero-badges"><DataBadge status="VALIDATED"/><span>7 islas · beta pública</span></div><h1>Salud infantil,<br/><em>territorio y evidencia.</em></h1><p>Observatorio independiente de salud infantil en Canarias basado en datos públicos, metodología reproducible y trazabilidad explícita.</p><div className="hero-actions"><Link className="primary-link" href="#mapa">Explorar mapa <span aria-hidden="true">↓</span></Link><Link href="/fuentes">Ver fuentes →</Link></div></div><div className="hero-note"><span className="note-number">07</span><div><strong>Las siete islas, siempre</strong><p>Explora accesibilidad, evolución, comparación territorial, contexto y resultados en la escala real de cada fuente.</p></div></div></section>
<nav className="home-quick-links" aria-label="Accesos principales"><Link href="#mapa">Explorar mapa</Link><Link href="/evolucion">Ver evolución</Link><Link href="/comparar">Comparar islas</Link><Link href="/pregunta">Preguntar a PedsData</Link><Link href="/fuentes">Ver fuentes</Link></nav>
<section className="summary-strip" aria-label="Indicadores de Canarias"><Metric metricId="child_population_grid_0_14" label="Población infantil" value={summary.children_0_14} detail="0–14 · ISTAC 2024"/><Metric metricId="verified_pediatric_facilities" label="Destinos pediátricos AP" value={summary.eligible_pediatric_facilities} detail="Centros verificados"/><Metric metricId="accessibility_ap" label="Mediana de acceso" value={summary.median_travel_minutes} suffix=" min" detail="Ponderada por niños"/><Metric metricId="income_mean_per_person" label="Municipios con renta" value={88} detail="INE ADRH 2023"/><Metric metricId="PM10" label="Estaciones de aire" value={airStations} detail="51 inventariadas · 49 en mapa"/></section>
<section className="map-section" id="mapa" aria-labelledby="map-title"><div className="section-heading"><div><span className="eyebrow">Mapa territorial</span><h2 id="map-title">Una capa principal, su escala y su unidad</h2></div><p>Cambia entre acceso, renta, densidad y contaminantes medidos. El mapa conserva la resolución real y ofrece una lectura tabular equivalente.</p></div><LazyAccessibilityMap municipalities={municipalities}/><SourceMethodPanel/></section>
<section className="ask-teaser"><div><span className="eyebrow">Pregunta a PedsData</span><h2>Pregunta; el catálogo decide qué es válido.</h2><p>Series, comparaciones y mapas con cálculo determinista y fuentes visibles.</p></div><Link className="primary-link" href="/pregunta">Abrir consulta controlada →</Link></section>
<section className="section context-board" id="entorno" aria-labelledby="context-title"><div className="section-heading"><div><span className="eyebrow">Contexto territorial infantil</span><h2 id="context-title">Medido, derivado y pendiente</h2></div><p>Cada dominio conserva su fecha, geografía y estado de validación.</p></div><div className="context-grid"><article><DataBadge status="COMPLETE"/><h3>Renta municipal</h3><strong>88 municipios</strong><p>Renta general del territorio; no se presenta como pobreza infantil.</p><ResultSourcesLink metricId="income_mean_per_person" period={2023} geography="municipality" result="Cobertura municipal de renta"/></article><article><DataBadge status="ESTIMATED"/><h3>Densidad y DEGURBA</h3><strong>255.814 niños</strong><p>Malla infantil 2024 sobre clasificación oficial 2021, sin score de ruralidad.</p><ResultSourcesLink metricId="child_density" period={2024} geography="municipality" result="Contexto territorial infantil"/></article><article><DataBadge status="PARTIAL"/><h3>Calidad del aire</h3><strong>{airStations} estaciones</strong><p>Valores de estación 2025; dos ubicaciones quedan sin coordenada validada para mapa.</p><ResultSourcesLink metricId="PM10" period={2025} geography="station" result="Estaciones de calidad del aire"/></article><article><DataBadge status="NOT AVAILABLE"/><h3>Meteorología y calima</h3><strong>Observaciones pendientes</strong><p>El inventario no se renderiza como indicador hasta disponer de observaciones trazables.</p></article></div></section>
<section className="section" id="islas" aria-labelledby="islands-title"><div className="section-heading"><div><span className="eyebrow">Siete perfiles insulares</span><h2 id="islands-title">Un archipiélago, siete contextos</h2></div><p>Ninguna isla desaparece por disponibilidad desigual.</p></div><IslandCards islands={islands}/></section>
<section className="clinical-teaser"><div><span className="eyebrow">Resultados de salud</span><h2>Clínica con escala explícita</h2><p>Hospitalización regional, prematuridad insular, urgencias hospitalarias, mortalidad multianual y estimaciones de encuesta sin forzar comparabilidad.</p></div><Link className="primary-link" href="/resultados">Explorar resultados <span aria-hidden="true">→</span></Link></section><AccessGapTable islands={islands}/>
<section className="section split-section" id="metodologia"><div><span className="eyebrow">Dotación · SIAP 2024</span><h2>{summary.pediatricians_ap_2024} pediatras AP</h2><p>Profesionales y edificios se mantienen separados. Las capas de contexto no modifican el cálculo de accesibilidad.</p><ResultSourcesLink metricId="pediatricians_ap" period={2024} geography="island" result="Dotación de Pediatría AP"/></div><div className="method-callout"><DataBadge status="PENDING OFFICIAL GEOMETRY"/><h3>Perfiles ZBS no publicados</h3><p>Los perfiles por Zona Básica de Salud no se publican actualmente porque no existe una geometría oficial vigente reutilizable validada para las siete islas.</p></div></section>
<section className="scientific-disclaimer" aria-label="Limitación científica"><strong>Lectura científica</strong><p>Los análisis territoriales describen asociaciones ecológicas y accesibilidad potencial. No estiman riesgo individual ni causalidad salvo que se indique expresamente.</p></section>
<div className="data-ribbon"><span>{metadata.source_period} · población</span><span>{metadata.income_period} · renta</span><span>{metadata.air_period} · aire validado</span><span>Beta pública · trazabilidad activa</span></div></>}
