"use client";
import {useEffect,useRef,useState} from "react";
import * as maplibregl from "maplibre-gl";
import type {Map as MapLibreMap,MapLayerMouseEvent} from "maplibre-gl";
import type {MunicipalityProfile} from "@/lib/types";
import {MapLegend,type ContextLayer} from "./MapLegend";
const BOUNDS:Record<string,[[number,number],[number,number]]>={"el-hierro":[[-18.2,27.6],[-17.85,27.9]],"la-gomera":[[-17.4,28],[-17,28.25]],"la-palma":[[-18,28.45],[-17.65,28.9]],tenerife:[[-16.95,27.95],[-16,28.65]],"gran-canaria":[[-15.85,27.7],[-15.35,28.2]],fuerteventura:[[-14.55,28],[-13.75,28.8]],lanzarote:[[-13.9,28.8],[-13.4,29.32]]};
const CANARY:[[number,number],[number,number]]=[[-18.35,27.45],[-13.25,29.45]];
const BAND:Record<string,string>={under_5:"Menos de 5 min","5_to_under_10":"5–<10 min","10_to_under_15":"10–<15 min","15_to_under_20":"15–<20 min","20_to_under_30":"20–<30 min","30_or_more":"30 min o más",requires_interisland_transfer:"Transferencia interinsular requerida",not_evaluated:"No evaluable"};
const layerLabel:Record<ContextLayer,string>={accessibility:"Accesibilidad pediátrica",income:"Renta por persona",density:"Densidad infantil",PM10:"PM10", "PM2.5":"PM2,5",NO2:"NO₂"};
export function AccessibilityMap({municipalities,initialIsland="all"}:{municipalities:MunicipalityProfile[];initialIsland?:string}){
 const container=useRef<HTMLDivElement>(null),mapRef=useRef<MapLibreMap|null>(null); const [island,setIsland]=useState(initialIsland),[municipality,setMunicipality]=useState("all"),[layer,setLayer]=useState<ContextLayer>("accessibility"),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[detail,setDetail]=useState<Record<string,unknown>|null>(null);
 useEffect(()=>{if(!container.current||mapRef.current)return; maplibregl.setWorkerUrl("/maplibre/maplibre-gl-worker.mjs"); const map=new maplibregl.Map({container:container.current,style:{version:8,sources:{},layers:[{id:"background",type:"background",paint:{"background-color":"#dfeae5"}}]},bounds:CANARY,fitBoundsOptions:{padding:28},attributionControl:false}); mapRef.current=map; map.addControl(new maplibregl.NavigationControl({showCompass:false}),"top-right"); map.addControl(new maplibregl.AttributionControl({customAttribution:"ISTAC · INE · Gobierno de Canarias · OSM"}));
 const init=()=>{map.addSource("municipalities",{type:"geojson",data:"/data/municipalities.geojson"}); map.addLayer({id:"municipality-fill",type:"fill",source:"municipalities",paint:{"fill-color":"#f7faf7","fill-opacity":.75}}); map.addLayer({id:"context-fill",type:"fill",source:"municipalities",layout:{visibility:"none"},paint:{"fill-color":"#d9e6dd","fill-opacity":.82,"fill-outline-color":"#fff"}}); map.addLayer({id:"municipality-line",type:"line",source:"municipalities",paint:{"line-color":"#78918b","line-width":.8}}); map.addSource("accessibility",{type:"geojson",data:"/data/accessibility-grid.geojson"}); map.addLayer({id:"accessibility-fill",type:"fill",source:"accessibility",paint:{"fill-color":["match",["get","band"],"under_5","#08766b","5_to_under_10","#43a685","10_to_under_15","#8ac58d","15_to_under_20","#d2d87f","20_to_under_30","#e6b65f","30_or_more","#cf704e","requires_interisland_transfer","#7552a3","#89928f"],"fill-opacity":.88,"fill-outline-color":"rgba(255,255,255,.3)"}}); map.addSource("facilities",{type:"geojson",data:"/data/facilities.geojson"}); map.addLayer({id:"facilities",type:"circle",source:"facilities",paint:{"circle-radius":3.5,"circle-color":"#102a36","circle-stroke-color":"#fff","circle-stroke-width":1}}); map.addSource("air",{type:"geojson",data:"/data/air-stations.geojson"}); map.addLayer({id:"air-stations",type:"circle",source:"air",layout:{visibility:"none"},paint:{"circle-radius":8,"circle-color":"#176b68","circle-stroke-color":"#fff","circle-stroke-width":2}});
 const click=(id:string)=>(e:MapLayerMouseEvent)=>{const p=e.features?.[0]?.properties;if(p)setDetail({...p,__layer:id})}; map.on("click","accessibility-fill",click("accessibility")); map.on("click","context-fill",click("context")); map.on("click","air-stations",click("air")); for(const id of ["accessibility-fill","context-fill","air-stations"]){map.on("mouseenter",id,()=>map.getCanvas().style.cursor="pointer");map.on("mouseleave",id,()=>map.getCanvas().style.cursor="")} map.once("idle",()=>setState("ready"));}; if(map.isStyleLoaded())init();else map.once("style.load",init); map.on("error",e=>{if(!map.isStyleLoaded())setState("error");console.error(e.error)}); return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||state!=="ready")return; const filters:unknown[]=[];if(island!=="all")filters.push(["==",["get","island_id"],island]);if(municipality!=="all")filters.push(["==",["get","municipality_id"],municipality]);const filter=filters.length===0?null:filters.length===1?filters[0]:["all",...filters]; for(const id of ["accessibility-fill","context-fill","air-stations"])map.setFilter(id,filter as never); map.setFilter("facilities",island==="all"?null:["==",["get","island_id"],island]); const access=layer==="accessibility"; map.setLayoutProperty("accessibility-fill","visibility",access?"visible":"none");map.setLayoutProperty("facilities","visibility",access?"visible":"none"); const contextual=layer==="income"||layer==="density"; map.setLayoutProperty("context-fill","visibility",contextual?"visible":"none"); map.setLayoutProperty("air-stations","visibility",!access&&!contextual?"visible":"none"); if(contextual){const property=layer==="income"?"income_mean_per_person_2023":"child_density_per_km2";const stops=layer==="income"?[10000,12000,14000]:[25,100,300];map.setPaintProperty("context-fill","fill-color",["step",["coalesce",["get",property],-1],"#c7d8cf",stops[0],"#9bc8b5",stops[1],"#55a48d",stops[2],"#176b68"] as never)} if(!access&&!contextual){const stops=layer==="PM2.5"?[5,10,20]:[10,20,40];map.setFilter("air-stations",["all",...(filters as never[]),["!=",["get",layer],null]] as never);map.setPaintProperty("air-stations","circle-color",["step",["get",layer],"#87c9b3",stops[0],"#d1d879",stops[1],"#e7a65c",stops[2],"#c95e4b"] as never)} map.fitBounds(island==="all"?CANARY:BOUNDS[island],{padding:38,duration:400});setDetail(null)},[island,municipality,layer,state]);
 const available=municipalities.filter(x=>island==="all"||x.island_id===island); const detailLayer=String(detail?.__layer||"");
 return <div className="map-shell"><div className="map-toolbar"><label>Ámbito insular<select value={island} onChange={e=>{setIsland(e.target.value);setMunicipality("all")}}><option value="all">Canarias · 7 islas</option>{Object.entries({"el-hierro":"El Hierro","la-gomera":"La Gomera","la-palma":"La Palma",tenerife:"Tenerife","gran-canaria":"Gran Canaria",fuerteventura:"Fuerteventura",lanzarote:"Lanzarote"}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Municipio<select value={municipality} onChange={e=>setMunicipality(e.target.value)}><option value="all">Todos los municipios</option>{available.map(x=><option key={`${x.island_id}-${x.municipality_id}`} value={x.municipality_id}>{x.municipality_name}</option>)}</select></label><label>Capa principal<select aria-label="Capa principal" value={layer} onChange={e=>setLayer(e.target.value as ContextLayer)}><option value="accessibility">Accesibilidad</option><option value="income">Renta</option><option value="density">Densidad infantil</option><option value="PM10">PM10</option><option value="PM2.5">PM2,5</option><option value="NO2">NO₂</option><option disabled>Temperatura · pendiente</option><option disabled>Calima · pendiente</option></select></label><span className="layer-label">{layerLabel[layer]}</span></div><div className="map-stage"><div ref={container} className="map" aria-label="Mapa de accesibilidad pediátrica de Canarias"/>{state==="loading"&&<div className="map-state" role="status">Cargando mapa validado…</div>}{state==="error"&&<div className="map-state" role="alert">El mapa no pudo cargarse. Los indicadores siguen disponibles.</div>}{detail&&<aside className="map-detail" aria-live="polite"><button onClick={()=>setDetail(null)} aria-label="Cerrar detalle">×</button><span className="eyebrow">{detailLayer==="air"?"Estación medida":detailLayer==="context"?"Contexto municipal":"Detalle de celda"}</span><strong>{detailLayer==="air"?String(detail.name):detailLayer==="context"?String(detail.municipality_name):BAND[String(detail.band)]??"Estado no disponible"}</strong>{detailLayer==="air"?<p>{detail[layer]==null?"Sin observación para esta variable":`${detail[layer]} µg/m³ · ${detail[`${layer}_date`]}`}<br/><small>Valor de estación; no representa toda la isla o municipio.</small></p>:detailLayer==="context"?<p>{layer==="income"?`${detail.income_mean_per_person_2023} €/persona · 2023`:`${detail.child_density_per_km2} niños/km² · 2024`}<br/><small>{layer==="income"?"Renta general; no equivale a pobreza infantil.":"Indicador municipal derivado de población 0–14."}</small></p>:<p>{String(detail.nearest_facility_name??"No asignado")} · {detail.distance_km==null?"distancia no disponible":`${detail.distance_km} km`}<br/><small>El conteo infantil exacto no se muestra.</small></p>}</aside>}</div><MapLegend layer={layer}/></div>
}
