"use client";
import {useMemo,useState} from "react";
import clinical from "@/data/clinical.json";
import {DataBadge} from "./DataBadge";
const islandNames:Record<string,string>={"el-hierro":"El Hierro","la-gomera":"La Gomera","la-palma":"La Palma",tenerife:"Tenerife","gran-canaria":"Gran Canaria",fuerteventura:"Fuerteventura",lanzarote:"Lanzarote"};
const format=(v:number|null,dec=0)=>v===null?"No disponible":new Intl.NumberFormat("es-ES",{maximumFractionDigits:dec}).format(v);
export function ClinicalExplorer(){
 const diagnoses=Array.from(new Map(clinical.hospitalization.map(r=>[r.diagnosis_group_id,r.diagnosis_group_name])).entries());
 const [diagnosis,setDiagnosis]=useState("lower_respiratory"),[age,setAge]=useState("Y_LT1"),[year,setYear]=useState("2024"),[surveyIndicator,setSurvey]=useState("problema_salud_mental");
 const selected=useMemo(()=>clinical.hospitalization.filter(r=>r.diagnosis_group_id===diagnosis&&r.age_group_code===age&&r.reference_period===year),[diagnosis,age,year]);
 const measure=(id:string)=>selected.find(r=>r.indicator_id===id)?.value??null;
 const trend=clinical.hospitalization.filter(r=>r.diagnosis_group_id===diagnosis&&r.age_group_code===age&&r.indicator_id==="altas");
 const max=Math.max(...trend.map(r=>r.value??0),1);
 const surveyNames=Array.from(new Map(clinical.survey.map(r=>[r.indicator_id,r.indicator_name])).entries());
 return <>
 <section className="clinical-module" id="hospitalizacion"><div className="module-head"><div><span className="eyebrow">Hospitalización · Canarias</span><h2>Edad y diagnóstico, sin falsa geografía</h2></div><DataBadge status="OBSERVED"/></div><p className="module-note">Residentes canarios dados de alta en cualquier hospital nacional. Estos datos no permiten comparar islas.</p>
 <div className="clinical-filters"><label>Grupo diagnóstico<select aria-label="Grupo diagnóstico" value={diagnosis} onChange={e=>setDiagnosis(e.target.value)}>{diagnoses.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Edad original<select aria-label="Edad hospitalización" value={age} onChange={e=>setAge(e.target.value)}><option value="Y_LT1">Menor de 1 año</option><option value="Y1T4">1–4 años</option><option value="Y5T14">5–14 años</option></select></label><label>Año<select aria-label="Año hospitalización" value={year} onChange={e=>setYear(e.target.value)}>{["2024","2023","2022","2021","2020"].map(v=><option key={v}>{v}</option>)}</select></label></div>
 <div className="clinical-kpis"><div><span>Altas</span><strong>{format(measure("altas"))}</strong><small>Episodios</small></div><div><span>Estancias</span><strong>{format(measure("estancia"))}</strong><small>Días</small></div><div><span>Estancia media</span><strong>{format(measure("estancia_media"),2)}</strong><small>Días</small></div></div>
 <div className="trend" aria-label="Tendencia de altas"><h3>Tendencia 2020–2024</h3>{trend.map(r=><div className="trend-row" key={r.reference_period}><span>{r.reference_period}</span><i style={{width:`${((r.value??0)/max)*100}%`}}/><strong>{format(r.value)}</strong></div>)}</div>
 </section>
 <section className="clinical-module" id="perinatal"><div className="module-head"><div><span className="eyebrow">Perinatal · 2024</span><h2>Prematuridad por isla de residencia materna</h2></div><DataBadge status="DERIVED_RATE"/></div><div className="table-scroll"><table><thead><tr><th>Isla</th><th>Nacimientos</th><th>Prematuros</th><th>Tasa</th></tr></thead><tbody>{Object.entries(islandNames).map(([id,name])=>{const rs=clinical.perinatal.filter(r=>r.geography_id===id),get=(x:string)=>rs.find(r=>r.indicator_id===x)?.value??null;return <tr key={id}><td>{name}</td><td>{format(get("births"))}</td><td>{format(get("preterm_births"))}</td><td>{format(get("preterm_rate"),2)} %</td></tr>})}</tbody></table></div></section>
 <section className="clinical-module" id="urgencias"><div className="module-head"><div><span className="eyebrow">Urgencias · hospital</span><h2>Una serie admitida, sin ranking</h2></div><DataBadge status="NOT_COMPARABLE"/></div><div className="clinical-kpis"><div><span>Urgencias CHUIMI</span><strong>{format(clinical.emergency.find(r=>r.indicator_id==="pediatric_ed_visits")?.value??null)}</strong><small>2024 · actividad hospitalaria</small></div><div><span>Ingresadas</span><strong>{format(clinical.emergency.find(r=>r.indicator_id==="admitted_from_ed")?.value??null)}</strong><small>No residentes únicos</small></div><div><span>Tasa de ingreso</span><strong>{format(clinical.emergency.find(r=>r.indicator_id==="admission_rate")?.value??null,2)} %</strong><small>Derivada</small></div></div><p className="module-note">Los otros ocho hospitales prioritarios permanecen NOT_AVAILABLE para una serie pediátrica homogénea.</p></section>
 <section className="clinical-module" id="mortalidad"><div className="module-head"><div><span className="eyebrow">Mortalidad · 2020–2024</span><h2>Ventanas multianuales y supresión explícita</h2></div><DataBadge status="MULTIYEAR_AGGREGATE"/></div><div className="table-scroll"><table><thead><tr><th>Isla</th><th>&lt;1 año</th><th>1–4</th><th>5–14</th></tr></thead><tbody>{Object.entries(islandNames).map(([id,name])=><tr key={id}><td>{name}</td>{["Y_LT1","Y1T4","Y5T14"].map(a=>{const r=clinical.mortality.find(x=>x.geography_id===id&&x.age_group_code===a);return <td key={a}>{r?.suppressed?"Suprimido 1–4":format(r?.value??null)}</td>})}</tr>)}</tbody></table></div><p className="module-note">Conteos de residentes, no tasas. Un cero observado se mantiene; un conteo 1–4 nunca se renderiza como cero.</p></section>
 <section className="clinical-module" id="salud-infantil"><div className="module-head"><div><span className="eyebrow">Encuesta de Salud · 2021</span><h2>Estimaciones en la geografía publicada</h2></div><DataBadge status="SURVEY_ESTIMATE"/></div><div className="clinical-filters single"><label>Indicador<select aria-label="Indicador encuesta" value={surveyIndicator} onChange={e=>setSurvey(e.target.value)}>{surveyNames.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div><div className="survey-grid">{clinical.survey.filter(r=>r.indicator_id===surveyIndicator).map(r=><article key={r.geography_id}><span>{r.geography_label}</span><strong>{format(r.value,2)} %</strong><small>Menores de 16 · SURVEY_ESTIMATE</small></article>)}</div></section>
 <section className="clinical-module research-card" id="research"><span className="eyebrow">Research mode · preparación</span><h2>Combinaciones válidas, análisis no automatizado</h2><div className="research-grid"><div><strong>Prematuridad × isla</strong><p>READY_FOR_DESCRIPTIVE · misma geografía y periodo.</p></div><div><strong>Hospitalización respiratoria × ambiente</strong><p>INSUFFICIENT_RESOLUTION · anual regional frente a estación diaria.</p></div><div><strong>Renta × ESC infantil</strong><p>RESEARCH_ONLY · escalas agrupadas y varianza de encuesta pendientes.</p></div></div></section>
 </>}
