import {expect,test} from "@playwright/test";

const criticalRoutes=["/","/evolucion","/comparar","/pregunta","/fuentes","/indicadores/accessibility_ap","/aviso","/licencias","/citar","/islas/lanzarote","/municipios/35001","/resultados"];

test("public beta home explains purpose, limits and five primary actions",async({page})=>{await page.goto("/");await expect(page.locator(".hero-badges").getByText(/7 islas · beta pública/i)).toBeVisible();for(const label of ["Explorar mapa","Ver evolución","Comparar islas","Preguntar a PedsData","Ver fuentes"])await expect(page.getByRole("link",{name:label,exact:true}).first()).toBeVisible();await expect(page.getByText(/Proyecto independiente basado en datos públicos/)).toBeVisible();await expect(page.getByText(/No estiman riesgo individual ni causalidad/)).toBeVisible();await expect(page.getByText(/RC3|RC4|RC5|preview/i)).toHaveCount(0)});

test("SEO endpoints and legal routes are public and explicit",async({page,request})=>{for(const route of ["/robots.txt","/sitemap.xml","/manifest.webmanifest"]){const response=await request.get(route);expect(response.ok(),route).toBe(true)}await page.goto("/aviso");await expect(page.getByRole("heading",{name:/No es una herramienta clínica/i})).toBeVisible();await page.goto("/licencias");await expect(page.getByText(/licencia MIT/i)).toBeVisible();await expect(page.getByText(/OpenStreetMap contributors/i)).toBeVisible();await page.goto("/citar");await expect(page.getByText(/No existe DOI asignado/i)).toBeVisible()});

test("keyboard landmarks, map text alternative and provenance are reachable",async({page})=>{await page.goto("/");await page.keyboard.press("Tab");await expect(page.getByRole("link",{name:"Saltar al contenido principal"})).toBeFocused();await page.locator("#mapa").scrollIntoViewIfNeeded();await expect(page.getByText("Alternativa textual del mapa")).toBeVisible();await expect(page.locator("main")).toHaveCount(1);await page.goto("/pregunta");await page.getByLabel("Pregunta a PedsData").fill("Evolución de pediatras en Lanzarote");await page.getByRole("button",{name:"Consultar"}).click();await expect(page.getByText("Fuentes registradas")).toBeVisible();await expect(page.getByText("Fuentes de este resultado").first()).toBeVisible()});

test("critical public routes remain unclipped and have one main landmark",async({page})=>{for(const route of criticalRoutes){await page.goto(route);await expect(page.locator("main")).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),route).toBe(true)}});
