import {expect,test} from "@playwright/test";

test("Gran Canaria report has executive findings, domains and separated regional context",async({page})=>{await page.goto("/informes/gran-canaria");await expect(page.getByRole("heading",{name:"Gran Canaria",level:1})).toBeVisible();await expect(page.getByRole("heading",{name:"Hallazgos calculados"})).toBeVisible();await expect(page.getByRole("heading",{name:"Utilización de Pediatría AP"})).toBeVisible();await expect(page.getByText("Contexto regional — no atribuible al territorio analizado")).toBeVisible();await expect(page.getByRole("heading",{name:/fuentes realmente usadas/i})).toBeVisible()});
test("Lanzarote report keeps La Graciosa transfer visible",async({page})=>{await page.goto("/informes/lanzarote");await expect(page.getByText(/Población con transferencia interinsular/)).toBeVisible();await expect(page.getByText(/91 niños/)).toBeVisible()});
test("El Hierro report remains attributable to island geography",async({page})=>{await page.goto("/informes/el-hierro");await expect(page.getByRole("heading",{name:"El Hierro",level:1})).toBeVisible();await expect(page.getByText("island").first()).toBeVisible()});
test("Telde report omits insular clinical attribution",async({page})=>{await page.goto("/informes/35026");await expect(page.getByRole("heading",{name:"Telde",level:1})).toBeVisible();await expect(page.getByRole("heading",{name:"Contexto socioeconómico"})).toBeVisible();await expect(page.locator("#perinatal")).toHaveCount(0);await expect(page.getByText(/Dato de Canarias. No se atribuye/).first()).toBeVisible()});
test("La Graciosa does not receive a fabricated road time",async({page})=>{await page.goto("/informes/la-graciosa");await expect(page.getByText("Transferencia interinsular requerida",{exact:true}).first()).toBeVisible();await expect(page.getByText(/No se genera un mapa de tiempo terrestre/)).toBeVisible();await expect(page.getByText(/Mediana de acceso potencial/)).toHaveCount(0)});
test("unknown territory returns not found",async({page})=>{const response=await page.goto("/informes/territorio-inexistente");expect(response?.status()).toBe(404)});
test("regional-only metrics remain inside regional context",async({page})=>{await page.goto("/informes/gran-canaria");const regional=page.locator("#regional-context");await expect(regional.getByRole("heading",{name:"Stock de espera en Pediatría",level:2})).toBeVisible();await expect(page.locator("article.territorial-report > section.territorial-domain").getByRole("heading",{name:"Stock de espera en Pediatría"})).toHaveCount(0)});
test("each report exposes result provenance",async({page})=>{await page.goto("/informes/gran-canaria");await expect(page.getByRole("link",{name:/Fuentes de este resultado/}).first()).toBeVisible();expect(await page.getByRole("link",{name:/Fuentes de este resultado/}).count()).toBeGreaterThan(5);await page.getByRole("link",{name:/Fuentes de este resultado/}).first().click();await expect(page).toHaveURL(/\/trazabilidad\//)});
test("Ask PedsData opens a territorial report",async({page})=>{await page.goto("/pregunta");await page.getByLabel("Pregunta a PedsData").fill("Hazme un informe exhaustivo de Gran Canaria");await page.getByRole("button",{name:"Consultar"}).click();await expect(page.getByText("TERRITORIAL_REPORT")).toBeVisible();await page.getByRole("link",{name:/Generar informe territorial de Gran Canaria/}).click();await expect(page).toHaveURL(/\/informes\/gran-canaria/)});
test("territorial report is mobile-safe and printable",async({page},testInfo)=>{test.skip(testInfo.project.name!=="iphone","mobile and print contract");await page.goto("/informes/35026");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);await page.emulateMedia({media:"print"});await expect(page.getByRole("button",{name:"Exportar / imprimir informe"})).toBeHidden();await expect(page.getByRole("heading",{name:"Telde",level:1})).toBeVisible()});
