import {describe,expect,it} from "vitest";
import {askPedsData} from "./semantic";
import {buildTerritorialReport,resolveTerritory} from "./territorial-report";

describe("territorial report planner",()=>{
 it.each(["gran-canaria","lanzarote","el-hierro"])("builds an island report for %s",id=>{const report=buildTerritorialReport(id)!;expect(report.territory.kind).toBe("island");expect(report.sections.length).toBeGreaterThan(4);expect(report.findings.length).toBeGreaterThanOrEqual(5);expect(report.sourceIds.length).toBeGreaterThan(0)});
 it("builds Telde only with municipality-compatible direct metrics",()=>{const report=buildTerritorialReport("35026")!;expect(report.territory.name).toBe("Telde");expect(report.sections.some(section=>section.id==="socioeconomic")).toBe(true);expect(report.sections.some(section=>section.id==="perinatal")).toBe(false);expect(report.regionalContext.every(section=>section.note?.includes("No se atribuye"))).toBe(true)});
 it("keeps La Graciosa as a limited component without fabricated times",()=>{const report=buildTerritorialReport("la-graciosa")!;expect(report.territory.publicationStatus).toBe("limited");expect(report.sections.flatMap(section=>section.facts).some(fact=>fact.value==="Transferencia interinsular requerida")).toBe(true);expect(report.sections.flatMap(section=>section.facts).some(fact=>typeof fact.value==="number"&&fact.metric_id==="accessibility_ap")).toBe(false)});
 it("returns null for a missing territory",()=>expect(resolveTerritory("atlantis")).toBeNull());
 it("keeps every rendered fact linked to registered sources",()=>{const report=buildTerritorialReport("gran-canaria")!;for(const fact of report.sections.flatMap(section=>section.facts)){expect(fact.source_ids.length).toBeGreaterThan(0);expect(fact.method_id).toBeTruthy();expect(fact.period).toBeTruthy();expect(fact.geography_id).toBe("gran-canaria")}});
 it("parses territorial report prompts without requiring a metric",()=>{const result=askPedsData("Hazme un informe exhaustivo de Gran Canaria");expect(result.ok).toBe(true);if(result.ok){expect(result.plan.intent).toBe("TERRITORIAL_REPORT");expect(result.report_href).toBe("/informes/gran-canaria");expect(result.source_ids.length).toBeGreaterThan(0)}});
 it("resolves a municipality by name",()=>{const result=askPedsData("Genera un perfil pediátrico de Telde");expect(result.ok).toBe(true);if(result.ok)expect(result.report_href).toBe("/informes/35026")});
 it("prioritizes a municipality when its name contains an island name",()=>{const result=askPedsData("Perfil pediátrico de Santa Cruz de Tenerife");expect(result.ok).toBe(true);if(result.ok)expect(result.report_name).toBe("Santa Cruz de Tenerife")});
 it("rejects a territorial report for an unknown place",()=>expect(askPedsData("Analiza Atlantis")).toMatchObject({ok:false,error:"GEOGRAPHY_NOT_SUPPORTED"}));
 it("creates deterministic, sourced editorial findings",()=>{const report=buildTerritorialReport("gran-canaria")!;const workforce=report.findings.find(item=>item.id==="workforce-balance")!;expect(workforce.text).toContain("Entre 2004 y 2024");expect(workforce.text).toContain("La relación pasó de");expect(workforce.metricIds).toEqual(["child_population_assigned_0_14","pediatricians_ap","assigned_children_per_pediatrician"]);expect(report.findings.every(item=>item.metricIds.length>0&&item.period.length>0)).toBe(true)});
 it("compares accessibility only at a registered island scale",()=>{const report=buildTerritorialReport("lanzarote")!;const comparison=report.findings.find(item=>item.id==="access-comparison")!;expect(comparison.text).toContain("conjunto de las siete islas");expect(comparison.metricIds).toEqual(["accessibility_ap"]);expect(buildTerritorialReport("35026")!.findings.some(item=>item.id==="access-comparison")).toBe(false)});
 it("adds responsible conclusions without causal or quality claims",()=>{const report=buildTerritorialReport("el-hierro")!;expect(report.interpretation.known.length).toBeGreaterThanOrEqual(3);expect(report.interpretation.cannotConclude.join(" ")).toContain("No permite atribuir causas");expect(report.interpretation.missingData).toContain("Geometría oficial vigente de Zonas Básicas de Salud para las siete islas");expect(report.findings.map(item=>item.text).join(" ").toLocaleLowerCase("es")).not.toContain("peor sistema")});
});
